#==============================================================================================================================================
# This file contains all the parameters used in the project
# You can change the values of the parameters to adapt the project to your needs
# You can also add new parameters if you need them.
#
# The all parameters are structured by categores to simplify the view and the use of the file
#
# DESCRIPTION OF THE PARAMETERS
# - data load parameters:
#   - MODEL_TARGET : string, "local" or "remote" #to move in .env
#   - OUTPUT_FORMAT : string, CNN class requers array representing the images as input,
#                    fixes the output format of sounds preprocessing, 'png' or 'npy'.
#   - SPECTOGRAM_TYPE : string, "MEL" precise the type of spectogram to use (right now only MEL is available)
#   - DATA_OUTPUT_FOLDER : string, "images_png" precise the folder where the spectrogram images will be saved
# - MEL spectogram variables
#   - SAMPLING_RATE: int, fixes the number of samples in 1s of sound,(in Hz)
#   - STFT_NUMBER_SAMPLES: int, fixes the number of samples in the STFT, (in Hz)
#   - HOP_OVERLAP: float, fixes the overlap between two STFT, (in Hz)
#   - N_MELS: int, mel scale the number of bands in the mel spectrogram
#   - HTK: int, break frequency
#   - F_MIN: int, minimum frequency of the spectrogram (in Hz)
#   - F_MAX: int, maximum frequency of the spectrogram (in Hz)
# - NN parameters
#   - MODEL_NAME: string, to choose from implemented DNN models collection in 'birdsong.model.model_collections.py',
#                 rigth now, you can choose between ["baseline_archi_0","baseline_archi_1","BirdNetBlock_a","BirdNetBlock_b"].
#   - MODEL_SAVE_PATH: string, wanted label of directory where to save the model. The directory will be created
#                      in the directory where 'birdsong' package is saved.
#   - CHECKPOINT_FOLDER_PATH: string, wanted label of directory where to save the model checkpoints. The directory
#                              will be created in the directory where 'birdsong' package is saved.
#   - RANDOM_SEED: int, random seed for reproducibility
#   - VALIDATION_SPLIT: float, proportion of the dataset to include in the train split 'data * (1 - VALIDATION_SPLIT)'.
#                       The proportion of datasate to include in the test split is fixed to 'data * VALIDATION_SPLIT * 1 / 3'.
#                       So the proportion of the dataset to include in the validation split is fixed to 'data * VALIDATION_SPLIT * 2 / 3'.
#   - BATCH_SIZE: int, number of samples per gradient update
#   - LEARNING_RATE: float, learning rate for tensorflow optimizers. we implemented today only Adam
#   - PATIENCE : int, argument patience in tensorflow EarlyStopping. Number of epochs with no improvement after which training will be stopped
# - sound augmenter encoders variables
#==============================================================================================================================================
# data load parameters
MODEL_TARGET : "local" #to move in .env
OUTPUT_FORMAT : "png"
SPECTOGRAM_TYPE : "MEL"
DATA_OUTPUT_FOLDER : "images_png_test"

# MEL spectogram variables
SAMPLING_RATE: 48000 #in (Hz)
STFT_NUMBER_SAMPLES: 512
HOP_OVERLAP: 0.25
N_MELS: 64 #mel scale with 64 bands
HTK: 1750 #break frequency
F_MIN: 150 #Hz
F_MAX: 15000 #Hz

# NN parameters
MODEL_NAME : 'baseline_archi_1' # you can choose between ["baseline_archi_0","baseline_archi_1","BirdNetBlock_a","BirdNetBlock_b"]
MODEL_SAVE_PATH: "model_save"
CHECKPOINT_FOLDER_PATH: "model_checkpoints"
RANDOM_SEED : 42
VALIDATION_SPLIT: 0.3
BATCH_SIZE : 32
LEARNING_RATE : 0.0005
PATIENCE : 5 #EarlyStopping


# sound augmenter encoders variables
ADD_SNR_NOISE: True
ADD_TIME_PITCH_SHIFT: True
ADD_REVERSE: True
MIN_SNR_DB : 5.0
MAX_SNR_DB : 40.0
PROBABILITY_SNR : 1.0
MIN_SHIFT: -0.5
MAX_SHIFT: 0.5
SHIFT_UNIT: "seconds"
PROBABILITY_SHIFT: 1.0
MIN_SEMITONES: -5
MAX_SEMITONES: 5
PROBABILITY_PITCH: 1.0
PROBABILITY_REVERSE: 1.0
