# slicer details
TRAIN_AUDIO_PATH : "train_audio"
SPLITED_DATA_PATH : "split_data"

# data load parameters
MODEL_TARGET : "local" #to move in .env
OUTPUT_FORMAT : "png"
SPECTOGRAM_TYPE : "MEL"
DATA_PERENT_DIR : "raw_data"
DATA_INPUT_FOLDER : "split_data"
DATA_OUTPUT_FOLDER : "images_png"

# NN parameters
MODEL_NAME : 'baseline_archi_1' # you can choose between ["baseline_archi_0","baseline_archi_1","BirdNetBlock_a","BirdNetBlock_b"]
MODEL_SAVE_PATH: "model_save"
CHECKPOINT_FOLDER_PATH: "model_checkpoints"
RANDOM_SEED : 42
VALIDATION_SPLIT: 0.3
TEST_SIZE_PART : 1
BATCH_SIZE : 32
LEARNING_RATE : 0.0005
PATIENCE : 5 #EarlyStopping

# sound augmenter encoders variables
MIN_SNR_DB : 5.0
MAX_SNR_DB : 40.0
PROBABILITY_SNR : 1.0
MIN_SHIFT: -0.01
MAX_SHIFT: 0.01
SHIFT_UNIT: "seconds"
PROBABILITY_SHIFT: 1.0
MIN_SEMITONES: -4
MAX_SEMITONES: 4
PROBABILITY_PITCH: 1.0

# MEL spectogram variables
SAMPLING_RATE: 48000 #window size of 10.7 ms (512 samples at 48 kHz)
DURATION_IN_SECONDS:  5  #seconds
READING_OFFSET: 0
STFT_NUMBER_SAMPLES: 512
HOP_OVERLAP: 0.25
N_MELS: 64 #mel scale with 64 bands
HTK: 1750 #break frequency
WINDOW_TYPE: "hann"
FEATURE: "mel"
F_MIN: 150 #Hz
F_MAX: 15000 #Hz
