
# sound encoders variables
MIN_SNR_DB : 5.0
MAX_SNR_DB : 40.0
PROBABILITY_SNR : 1.0
MIN_SHIFT: -0.01
MAX_SHIFT: 0.01
SHIFT_UNIT: "seconds"
PROBABILITY_SHIFT: 1.0
MIN_SEMITONES: -4
MAX_SEMITONES: 4
PROBABILITY_PITCH: 1.0
